import type { Metadata } from 'next';
import '../core/styles/globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className='antialiased'>{children}</body>
    </html>
  );
};

export default RootLayout;
