import type { Metadata } from 'next';

import { Button } from 'components/ui';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div>
      <h1 className='text-red-500'>Hello</h1>
      <Button>
        <p>Button</p>
      </Button>
    </div>
  );
}
